<svelte:head>
	<title>WebDev</title>
	<meta name="description" content="About this app" />
</svelte:head>

<script>
    import gif from '$lib/images/123.gif';
    import logo22 from '$lib/images/logo22.webp';



import { onMount } from 'svelte';

	let time = new Date();

	// these automatically update when `time`
	// changes, because of the `$:` prefix
	$: hours = time.getHours();
	$: minutes = time.getMinutes();
	$: seconds = time.getSeconds();

	onMount(() => {
		const interval = setInterval(() => {
			time = new Date();
		}, 1000);

		return () => {
			clearInterval(interval);
		};
	});
</script>

<svg viewBox="-50 -50 100 100">
	<circle class="clock-face" r="48" />

	<!-- markers -->
	{#each [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55] as minute}
		<line class="major" y1="35" y2="45" transform="rotate({30 * minute})" />

		{#each [1, 2, 3, 4] as offset}
			<line class="minor" y1="42" y2="45" transform="rotate({6 * (minute + offset)})" />
		{/each}
	{/each}

	<!-- hour hand -->
	<line class="hour" y1="2" y2="-20" transform="rotate({30 * hours + minutes / 2})" />

	<!-- minute hand -->
	<line class="minute" y1="4" y2="-30" transform="rotate({6 * minutes + seconds / 10})" />

	<!-- second hand -->
	<g transform="rotate({6 * seconds})">
		<line class="second" y1="10" y2="-38" />
		<line class="second-counterweight" y1="10" y2="2" />
	</g>
</svg>

<style>
	svg {
		width: 100%;
		height: 100%;
	}

	.clock-face {
		stroke: #333;
		fill: white;
	}

	.minor {
		stroke: #999;
		stroke-width: 0.5;
	}

	.major {
		stroke: #333;
		stroke-width: 1;
	}

	.hour {
		stroke: #333;
	}

	.minute {
		stroke: #666;
	}

	.second,
	.second-counterweight {
		stroke: rgb(180, 0, 0);
	}

	.second-counterweight {
		stroke-width: 3;
	}
</style>

<h1><pre><a href="/">HOME</a></pre></h1>
<img alt="The project logo" src={gif} />
<img alt="The project logo" src={logo22} />
/* App.svelte generated by Svelte v4.2.8 */
import {
	SvelteComponentDev,
	add_location,
	append_dev,
	append_styles,
	attr_dev,
	destroy_each,
	detach_dev,
	dispatch_dev,
	empty,
	ensure_array_like_dev,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	svg_element,
	validate_slots
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { onMount } from 'svelte';
const file = "App.svelte";

function add_css(target) {
	append_styles(target, "svelte-1kjtqer", "svg.svelte-1kjtqer{width:100%;height:100%}.clock-face.svelte-1kjtqer{stroke:#333;fill:white}.minor.svelte-1kjtqer{stroke:#999;stroke-width:0.5}.major.svelte-1kjtqer{stroke:#333;stroke-width:1}.hour.svelte-1kjtqer{stroke:#333}.minute.svelte-1kjtqer{stroke:#666}.second.svelte-1kjtqer,.second-counterweight.svelte-1kjtqer{stroke:rgb(180, 0, 0)}.second-counterweight.svelte-1kjtqer{stroke-width:3}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQXBwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiQXBwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuXHRpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcblxuXHRsZXQgdGltZSA9IG5ldyBEYXRlKCk7XG5cblx0Ly8gdGhlc2UgYXV0b21hdGljYWxseSB1cGRhdGUgd2hlbiBgdGltZWBcblx0Ly8gY2hhbmdlcywgYmVjYXVzZSBvZiB0aGUgYCQ6YCBwcmVmaXhcblx0JDogaG91cnMgPSB0aW1lLmdldEhvdXJzKCk7XG5cdCQ6IG1pbnV0ZXMgPSB0aW1lLmdldE1pbnV0ZXMoKTtcblx0JDogc2Vjb25kcyA9IHRpbWUuZ2V0U2Vjb25kcygpO1xuXG5cdG9uTW91bnQoKCkgPT4ge1xuXHRcdGNvbnN0IGludGVydmFsID0gc2V0SW50ZXJ2YWwoKCkgPT4ge1xuXHRcdFx0dGltZSA9IG5ldyBEYXRlKCk7XG5cdFx0fSwgMTAwMCk7XG5cblx0XHRyZXR1cm4gKCkgPT4ge1xuXHRcdFx0Y2xlYXJJbnRlcnZhbChpbnRlcnZhbCk7XG5cdFx0fTtcblx0fSk7XG48L3NjcmlwdD5cblxuPHN2ZyB2aWV3Qm94PVwiLTUwIC01MCAxMDAgMTAwXCI+XG5cdDxjaXJjbGUgY2xhc3M9XCJjbG9jay1mYWNlXCIgcj1cIjQ4XCIgLz5cblxuXHQ8IS0tIG1hcmtlcnMgLS0+XG5cdHsjZWFjaCBbMCwgNSwgMTAsIDE1LCAyMCwgMjUsIDMwLCAzNSwgNDAsIDQ1LCA1MCwgNTVdIGFzIG1pbnV0ZX1cblx0XHQ8bGluZSBjbGFzcz1cIm1ham9yXCIgeTE9XCIzNVwiIHkyPVwiNDVcIiB0cmFuc2Zvcm09XCJyb3RhdGUoezMwICogbWludXRlfSlcIiAvPlxuXG5cdFx0eyNlYWNoIFsxLCAyLCAzLCA0XSBhcyBvZmZzZXR9XG5cdFx0XHQ8bGluZSBjbGFzcz1cIm1pbm9yXCIgeTE9XCI0MlwiIHkyPVwiNDVcIiB0cmFuc2Zvcm09XCJyb3RhdGUoezYgKiAobWludXRlICsgb2Zmc2V0KX0pXCIgLz5cblx0XHR7L2VhY2h9XG5cdHsvZWFjaH1cblxuXHQ8IS0tIGhvdXIgaGFuZCAtLT5cblx0PGxpbmUgY2xhc3M9XCJob3VyXCIgeTE9XCIyXCIgeTI9XCItMjBcIiB0cmFuc2Zvcm09XCJyb3RhdGUoezMwICogaG91cnMgKyBtaW51dGVzIC8gMn0pXCIgLz5cblxuXHQ8IS0tIG1pbnV0ZSBoYW5kIC0tPlxuXHQ8bGluZSBjbGFzcz1cIm1pbnV0ZVwiIHkxPVwiNFwiIHkyPVwiLTMwXCIgdHJhbnNmb3JtPVwicm90YXRlKHs2ICogbWludXRlcyArIHNlY29uZHMgLyAxMH0pXCIgLz5cblxuXHQ8IS0tIHNlY29uZCBoYW5kIC0tPlxuXHQ8ZyB0cmFuc2Zvcm09XCJyb3RhdGUoezYgKiBzZWNvbmRzfSlcIj5cblx0XHQ8bGluZSBjbGFzcz1cInNlY29uZFwiIHkxPVwiMTBcIiB5Mj1cIi0zOFwiIC8+XG5cdFx0PGxpbmUgY2xhc3M9XCJzZWNvbmQtY291bnRlcndlaWdodFwiIHkxPVwiMTBcIiB5Mj1cIjJcIiAvPlxuXHQ8L2c+XG48L3N2Zz5cblxuPHN0eWxlPlxuXHRzdmcge1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC5jbG9jay1mYWNlIHtcblx0XHRzdHJva2U6ICMzMzM7XG5cdFx0ZmlsbDogd2hpdGU7XG5cdH1cblxuXHQubWlub3Ige1xuXHRcdHN0cm9rZTogIzk5OTtcblx0XHRzdHJva2Utd2lkdGg6IDAuNTtcblx0fVxuXG5cdC5tYWpvciB7XG5cdFx0c3Ryb2tlOiAjMzMzO1xuXHRcdHN0cm9rZS13aWR0aDogMTtcblx0fVxuXG5cdC5ob3VyIHtcblx0XHRzdHJva2U6ICMzMzM7XG5cdH1cblxuXHQubWludXRlIHtcblx0XHRzdHJva2U6ICM2NjY7XG5cdH1cblxuXHQuc2Vjb25kLFxuXHQuc2Vjb25kLWNvdW50ZXJ3ZWlnaHQge1xuXHRcdHN0cm9rZTogcmdiKDE4MCwgMCwgMCk7XG5cdH1cblxuXHQuc2Vjb25kLWNvdW50ZXJ3ZWlnaHQge1xuXHRcdHN0cm9rZS13aWR0aDogMztcblx0fVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFnREMsa0JBQUksQ0FDSCxLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUNULENBRUEsMEJBQVksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUNaLElBQUksQ0FBRSxLQUNQLENBRUEscUJBQU8sQ0FDTixNQUFNLENBQUUsSUFBSSxDQUNaLFlBQVksQ0FBRSxHQUNmLENBRUEscUJBQU8sQ0FDTixNQUFNLENBQUUsSUFBSSxDQUNaLFlBQVksQ0FBRSxDQUNmLENBRUEsb0JBQU0sQ0FDTCxNQUFNLENBQUUsSUFDVCxDQUVBLHNCQUFRLENBQ1AsTUFBTSxDQUFFLElBQ1QsQ0FFQSxzQkFBTyxDQUNQLG9DQUFzQixDQUNyQixNQUFNLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQ3RCLENBRUEsb0NBQXNCLENBQ3JCLFlBQVksQ0FBRSxDQUNmIn0= */");
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[4] = list[i];
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[7] = list[i];
	return child_ctx;
}

// (30:2) {#each [1, 2, 3, 4] as offset}
function create_each_block_1(ctx) {
	let line;
	let line_transform_value;

	const block = {
		c: function create() {
			line = svg_element("line");
			attr_dev(line, "class", "minor svelte-1kjtqer");
			attr_dev(line, "y1", "42");
			attr_dev(line, "y2", "45");
			attr_dev(line, "transform", line_transform_value = "rotate(" + 6 * (/*minute*/ ctx[4] + /*offset*/ ctx[7]) + ")");
			add_location(line, file, 30, 3, 673);
		},
		m: function mount(target, anchor) {
			insert_dev(target, line, anchor);
		},
		p: noop,
		d: function destroy(detaching) {
			if (detaching) {
				detach_dev(line);
			}
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_each_block_1.name,
		type: "each",
		source: "(30:2) {#each [1, 2, 3, 4] as offset}",
		ctx
	});

	return block;
}

// (27:1) {#each [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55] as minute}
function create_each_block(ctx) {
	let line;
	let line_transform_value;
	let each_1_anchor;
	let each_value_1 = ensure_array_like_dev([1, 2, 3, 4]);
	let each_blocks = [];

	for (let i = 0; i < 4; i += 1) {
		each_blocks[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	const block = {
		c: function create() {
			line = svg_element("line");

			for (let i = 0; i < 4; i += 1) {
				each_blocks[i].c();
			}

			each_1_anchor = empty();
			attr_dev(line, "class", "major svelte-1kjtqer");
			attr_dev(line, "y1", "35");
			attr_dev(line, "y2", "45");
			attr_dev(line, "transform", line_transform_value = "rotate(" + 30 * /*minute*/ ctx[4] + ")");
			add_location(line, file, 27, 2, 563);
		},
		m: function mount(target, anchor) {
			insert_dev(target, line, anchor);

			for (let i = 0; i < 4; i += 1) {
				if (each_blocks[i]) {
					each_blocks[i].m(target, anchor);
				}
			}

			insert_dev(target, each_1_anchor, anchor);
		},
		p: noop,
		d: function destroy(detaching) {
			if (detaching) {
				detach_dev(line);
				detach_dev(each_1_anchor);
			}

			destroy_each(each_blocks, detaching);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(27:1) {#each [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55] as minute}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let svg;
	let circle;
	let line0;
	let line0_transform_value;
	let line1;
	let line1_transform_value;
	let g;
	let line2;
	let line3;
	let g_transform_value;
	let each_value = ensure_array_like_dev([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]);
	let each_blocks = [];

	for (let i = 0; i < 12; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const block = {
		c: function create() {
			svg = svg_element("svg");
			circle = svg_element("circle");

			for (let i = 0; i < 12; i += 1) {
				each_blocks[i].c();
			}

			line0 = svg_element("line");
			line1 = svg_element("line");
			g = svg_element("g");
			line2 = svg_element("line");
			line3 = svg_element("line");
			attr_dev(circle, "class", "clock-face svelte-1kjtqer");
			attr_dev(circle, "r", "48");
			add_location(circle, file, 23, 1, 439);
			attr_dev(line0, "class", "hour svelte-1kjtqer");
			attr_dev(line0, "y1", "2");
			attr_dev(line0, "y2", "-20");
			attr_dev(line0, "transform", line0_transform_value = "rotate(" + (30 * /*hours*/ ctx[2] + /*minutes*/ ctx[1] / 2) + ")");
			add_location(line0, file, 35, 1, 797);
			attr_dev(line1, "class", "minute svelte-1kjtqer");
			attr_dev(line1, "y1", "4");
			attr_dev(line1, "y2", "-30");
			attr_dev(line1, "transform", line1_transform_value = "rotate(" + (6 * /*minutes*/ ctx[1] + /*seconds*/ ctx[0] / 10) + ")");
			add_location(line1, file, 38, 1, 906);
			attr_dev(line2, "class", "second svelte-1kjtqer");
			attr_dev(line2, "y1", "10");
			attr_dev(line2, "y2", "-38");
			add_location(line2, file, 42, 2, 1059);
			attr_dev(line3, "class", "second-counterweight svelte-1kjtqer");
			attr_dev(line3, "y1", "10");
			attr_dev(line3, "y2", "2");
			add_location(line3, file, 43, 2, 1102);
			attr_dev(g, "transform", g_transform_value = "rotate(" + 6 * /*seconds*/ ctx[0] + ")");
			add_location(g, file, 41, 1, 1019);
			attr_dev(svg, "viewBox", "-50 -50 100 100");
			attr_dev(svg, "class", "svelte-1kjtqer");
			add_location(svg, file, 22, 0, 406);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, svg, anchor);
			append_dev(svg, circle);

			for (let i = 0; i < 12; i += 1) {
				if (each_blocks[i]) {
					each_blocks[i].m(svg, null);
				}
			}

			append_dev(svg, line0);
			append_dev(svg, line1);
			append_dev(svg, g);
			append_dev(g, line2);
			append_dev(g, line3);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*hours, minutes*/ 6 && line0_transform_value !== (line0_transform_value = "rotate(" + (30 * /*hours*/ ctx[2] + /*minutes*/ ctx[1] / 2) + ")")) {
				attr_dev(line0, "transform", line0_transform_value);
			}

			if (dirty & /*minutes, seconds*/ 3 && line1_transform_value !== (line1_transform_value = "rotate(" + (6 * /*minutes*/ ctx[1] + /*seconds*/ ctx[0] / 10) + ")")) {
				attr_dev(line1, "transform", line1_transform_value);
			}

			if (dirty & /*seconds*/ 1 && g_transform_value !== (g_transform_value = "rotate(" + 6 * /*seconds*/ ctx[0] + ")")) {
				attr_dev(g, "transform", g_transform_value);
			}
		},
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) {
				detach_dev(svg);
			}

			destroy_each(each_blocks, detaching);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let hours;
	let minutes;
	let seconds;
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots('App', slots, []);
	let time = new Date();

	onMount(() => {
		const interval = setInterval(
			() => {
				$$invalidate(3, time = new Date());
			},
			1000
		);

		return () => {
			clearInterval(interval);
		};
	});

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== '$$' && key !== 'slot') console.warn(`<App> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({ onMount, time, seconds, minutes, hours });

	$$self.$inject_state = $$props => {
		if ('time' in $$props) $$invalidate(3, time = $$props.time);
		if ('seconds' in $$props) $$invalidate(0, seconds = $$props.seconds);
		if ('minutes' in $$props) $$invalidate(1, minutes = $$props.minutes);
		if ('hours' in $$props) $$invalidate(2, hours = $$props.hours);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*time*/ 8) {
			// these automatically update when `time`
			// changes, because of the `$:` prefix
			$: $$invalidate(2, hours = time.getHours());
		}

		if ($$self.$$.dirty & /*time*/ 8) {
			$: $$invalidate(1, minutes = time.getMinutes());
		}

		if ($$self.$$.dirty & /*time*/ 8) {
			$: $$invalidate(0, seconds = time.getSeconds());
		}
	};

	return [seconds, minutes, hours, time];
}

class App extends SvelteComponentDev {
	constructor(options) {
		super(options);
		init(this, options, instance, create_fragment, safe_not_equal, {}, add_css);

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}

export default App;